### ISSUE TITLE
Cannot find refs from repo root

### ISSUE THREAD

**Issue by riedgar-ms** [Holzhaus/sphinx-multiversion#29] opened 2020-08-05 16:57 UTC
Following the quickstart page, I'm running ` sphinx-multiversion.exe .\docs\ build/html` from my repo root. This is failing to find anything:
```
(py-36) PS C:\Users\riedgar\source\repos\fairlearn> sphinx-multiversion.exe .\docs\ build/html
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
C:\Users\riedgar\source\repos\fairlearn
C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts\sphinx-multiversion.exe
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\python36.zip
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\DLLs
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36
C:\Users\riedgar\AppData\Roaming\Python\Python36\site-packages
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages
c:\users\riedgar\source\repos\fairlearn
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\win32\lib
c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\site-packages\Pythonwin
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
0.4.7.dev0
================================
No matching refs found!
```
Changing the command to `sphinx-build.exe .\docs\ build/html`  results in the documentation being built without issue.

There are plenty of tags to be found:
```
(py-36) PS C:\Users\riedgar\source\repos\fairlearn> git tag
release-0.3.0a-2019-10-30
v0.1
v0.2.0
v0.3.0
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
```
(although only the last of them will have buildable documentation). There are also a number of local branches. And I do not set any of the `smv_` variables in the `conf.py`.

Am I missing something? This is using Python 3.6 on Windows.

**Comment by Holzhaus** [comment] 2020-08-05 17:09
I'm confused by your mix of forward and backward slashes that you use in paths. I don't know if this will cause a problem on Windows.

You can check which refs sphinx-multiversion detects by using `--dump-metadata` although it seems like nothing is detected at all.

You can also try to use the latest master version. I merged a PR that fixes a Windows compatibility issues a few ours ago: #19

**Comment by riedgar-ms** [comment] 2020-08-05 17:20
I believe the mixed slashes are because I type forward slashes instinctively but when I tab complete, PowerShell changes them to backslashes. I should have added that `--dump-metadata` was returning an empty set.

I did `pip install git+https://github.com/Holzhaus/sphinx-multiversion.git` and it is looking promising for building the docs (our doc build runs examples, so each version will take a while).

**Comment by riedgar-ms** [comment] 2020-08-05 19:10
Now I'm trying to restrict what gets build. I've added the following to my `conf.py`:
```python
smv_tag_whitelist = r'^v0\.4\.6$'
smv_branch_whitelist = r'^master$'
```
However on running `sphinx-multiversion.exe .\docs\ build\html --dump-metadata`, there's an error:
```
Failed load config for refs/tags/v0.4.6 from C:\Users\riedgar\AppData\Local\Temp\tmp5jz52gc_\66894d7d7cdf663a2caa51bf4d31f080e242b2af\docs
```
However, `conf.py` does exist in that tag:
https://github.com/fairlearn/fairlearn/blob/v0.4.6/docs/conf.py

**Comment by Holzhaus** [comment] 2020-08-06 11:04
The problem is that the `conf.py` throws an error:

    AttributeError: module 'fairlearn' has no attribute '_base_version'

That happens because Python doesn't reload the `fairlearn` module after the inital load. Check PR #30 that attempts to work around that issue by using a separate processes to load the config. Might come with a performance penalty though (especially on windows, were process creation is expensive).

**Comment by riedgar-ms** [comment] 2020-08-06 15:14
Thanks. That gets past that error (onto another one now, but I need to figure out whether that's a multiversion one or not). The performance penalty from process creation isn't going to be significant for our particular case, since our documentation includes examples which train some (simple) ML models.

**Comment by Holzhaus** [comment] 2020-08-06 17:54
You can also pull the changes from #28 into the same branch, that probably fixes the build error.

**Comment by riedgar-ms** [comment] 2020-08-06 18:24
I've merged that branch in, but I'm still getting the error:
```
Extension error:
Example directory C:\Users\riedgar\AppData\Local\Temp\tmpqq_7azo3\66894d7d7cdf663a2caa51bf4d31f080e242b2af\docs\../examples/quickstart does not have a README file with one of the expected file extensions ['.txt', '.rst']. Please write one to introduce your gallery.
Traceback (most recent call last):
  File "C:\Users\riedgar\AppData\Local\Continuum\miniconda3\envs\py-36\Scripts\sphinx-multiversion-script.py", line 33, in <module>
    sys.exit(load_entry_point('sphinx-multiversion', 'console_scripts', 'sphinx-multiversion')())
  File "c:\users\riedgar\source\repos\sphinx-multiversion\sphinx_multiversion\main.py", line 288, in main
    subprocess.check_call(cmd)
  File "c:\users\riedgar\appdata\local\continuum\miniconda3\envs\py-36\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('c:\\users\\riedgar\\appdata\\local\\continuum\\miniconda3\\envs\\py-36\\python.exe', '-m', 'sphinx', '-D', 'smv_metadata_path=C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpqq_7azo3\\versions.json', '-D', 'smv_current_version=v0.4.6', '-c', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs', 'C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmpqq_7azo3\\66894d7d7cdf663a2caa51bf4d31f080e242b2af\\docs', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\v0.4.6')' returned non-zero exit status 2.
```
This doesn't happen if I checkout the tag and run `sphinx-build`.

**Comment by Holzhaus** [comment] 2020-08-06 21:24
Ah, we also need to set the cwd correctly. I'll add a fix.

**Comment by Holzhaus** [comment] 2020-08-06 21:33
Ok, please pull the latest state from #30 and check again.

**Comment by riedgar-ms** [comment] 2020-08-06 22:06
That completes without error, but there's only a `master` directory under `build/html`. If I run `--dump-metadata` I get:
```
Failed load config for refs/tags/v0.4.6 from C:\Users\riedgar\AppData\Local\Temp\tmp21f_ke0y\66894d7d7cdf663a2caa51bf4d31f080e242b2af\docs
```

In case I messed up, I deleted my previous clone and did:
```
git clone https://github.com/Holzhaus/sphinx-multiversion.git
cd .\sphinx-multiversion\
pip install -e .
git checkout sphinx-build-subprocess
```
and then went back to our project, and ran `sphinx-multiversion`.

**Comment by Holzhaus** [comment] 2020-08-06 22:13
You need the changes from both #28 and #30. 

In addition to the commands above, run:

    git pull origin separate-config-process

Does it work then?

**Comment by riedgar-ms** [comment] 2020-08-06 22:59
That goes back to:
```
Extension error:
Example directory C:\Users\riedgar\AppData\Local\Temp\tmpvjvj4hf6\66894d7d7cdf663a2caa51bf4d31f080e242b2af\docs\../examples/quickstart does not have a README file with one of the expected file extensions ['.txt', '.rst']. Please write one to introduce your gallery.
```
If you want to look at the actual repo:
https://github.com/riedgar-ms/fairlearn/tree/riedgar-ms/versioned-docs-01

**Comment by Holzhaus** [comment] 2020-08-06 23:32
No, the problem is that we're trying to build the 0.4.6 tag with the current config from master. This is done to support repositories that haven't been set up to use sphinx-multiversion from the start (setting a compatible theme, adding a version template, etc), because editing old branches and tags is not feasible.

In your case, sphinx galleries is configured differently in those two `conf.py` files, So using the new `conf.py` to build that old branch won't work

I'm unsure how to fix that problem. If you have an idea, please let me know.

**Comment by riedgar-ms** [comment] 2020-08-06 23:40
That makes a horrible amount of sense. The reason I'm investigating versioned documentation is that we've had so many breaking changes in `master` since the v0.4.6 release that we wanted to have an alternative set of documentation to which we could send people.

Would it be possible to do each individual build with its own `conf.py`? I can appreciate the desire for standardising on one, but if the `conf.py` from `master` is forced on every branch, doesn't that severely restrict the changes that can be made to `conf.py`?

**Comment by Holzhaus** [comment] 2020-08-07 08:53
> if the conf.py from master is forced on every branch, doesn't that severely restrict the changes that can be made to conf.py?

Yes, but I don't see a real alternative tbh.

> Would it be possible to do each individual build with its own conf.py?

Not really. In that case you not only have no consistent theme (if you changed it between versions), also the versioning template would be missing from old branches (i.e. there'll be no links from old versions to the new one) and the sphinx-multiversion extension wouldn't even be loaded so all the HTML context variables wouldn't be set.

Basically, there would be no difference to a regular shell script that just checks out each branch/tag individually and just run the regular sphinx-build executable to build them.

Maybe we could make it possible to allow specifying overrides per-version, but I don't think that this would help in all cases.

**Comment by riedgar-ms** [comment] 2020-08-07 12:11
OK, well let's close this issue for now, since there are fixes available for the bugs which were preventing me from building at all. I'll have a think about how best to handle our particular situation, with breaking `conf.py` changes.

Thank you for your quick replies and help debugging this.

**Closed** 2020-08-08 10:04 UTC

**Comment by Holzhaus** [comment] 2020-08-11 15:24
> I'll have a think about how best to handle our particular situation, with breaking `conf.py` changes.

Have you considered adding a dict with possible sphinx gallery directories to the master branch's `conf.py` and check which one of these actually exists before passing them to sphinx gallery? I think that should solve your issue.

**Comment by riedgar-ms** [comment] 2020-08-14 18:23
Just prodding your suggestion now.... how do I detect the version currently being built inside `conf.py`? The [documentation notes that](https://holzhaus.github.io/sphinx-multiversion/master/configuration.html#overriding-configuration-variables) "relative paths in your conf.py will refer to the path of the version you’re building from, not the path of the version you are trying to build documentation for." Also, when the documentation build is actually running, I'm finding that the version reported for my target library is that of the version I'm building from, and not the version currently being built.

**Comment by Holzhaus** [comment] 2020-08-14 18:43
I think the documentation might incorrect now that we build in a separate process. Can you verify if relative paths are in fact relative to the version you're building from?

**Comment by riedgar-ms** [comment] 2020-08-14 19:04
In my `conf.py` I've added the lines:
```python
print("release=", fairlearn.__version__)
print("cwd=", os.getcwd())
```
immediately before `sphinx_gallery_conf` is set. It's printing:
```
release= 0.4.7.dev0
cwd= C:\Users\riedgar\source\repos\fairlearn\docs
```
each time, including the crash on the (old) v0.4.6:
```
subprocess.CalledProcessError: Command '('c:\\users\\riedgar\\appdata\\local\\continuum\\miniconda3\\envs\\py-36\\python.exe', '-R', '-m', 'sphinx', '-D', 'smv_metadata_path=C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmp4gi9j79p\\versions.json', '-D', 'smv_current_version=v0.4.6', '-c', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\docs', 'C:\\Users\\riedgar\\AppData\\Local\\Temp\\tmp4gi9j79p\\66894d7d7cdf663a2caa51bf4d31f080e242b2af\\docs', 'C:\\Users\\riedgar\\source\\repos\\fairlearn\\build\\html\\v0.4.6')' returned non-zero exit status 2.
```
which was obviously trying to build the troublesome v0.4.6.

This is from a `pip install -e .` of a pull of `master` from the `sphinx-multiversion` repo.
